version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - APP_ENV=development
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    # If needed, you can add env_file to load variables from .env
    # env_file:
    #   - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules # To avoid overwriting with local node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    depends_on:
      - backend
